name = "Cobblemon Rally"
author = "Sqishy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "372e99054c39f2dfe19e97a4f2d77f9b1a91c0ad9883df954b850d059d8abe2e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
