name = "Cobblemon Rally"
author = "Sqishy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "173d1b1a064e23c7755d52f518c273ed077cd02c93f8a52dd3bba2e0c27c913c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
