name = "Cobblemon Rally"
author = "Sqishy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac2cfca88d403ce9208341b26018dfc82a2070451d1ffdc027ccd0ca6f3be7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
